#define MENU_MAIN 100
#define ID_FILE_EXIT 101
#define ID_HELP_ABOUT 102
#define IDC_MONITORINFO 103

#define ID_MENU_BANANA 200
#define IDB_BANANA_IMAGE 201
#define IDD_BANANA_DIALOG 202
#define IDC_BANANA_PICTURE 203

#define ID_MENU_LOWRESPIC 300
#define IDB_LOWRESPIC_IMAGE 301
#define IDD_LOWRESPIC_DIALOG 302
#define IDC_LOWRESPIC_PICTURE 303

#define ID_SOUND_ROAR 400
#define IDS_ROAR_SOUND 401
#define IDC_PLAY_ROAR 402

#define IDD_WARNING_DIALOG 500
#define ID_YES 501
#define ID_NO 502
#define IDC_RICHEDIT 503
#define IDC_STATIC 600
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
