#define MENU_MAIN 100
#define ID_FILE_EXIT 101
#define ID_HELP_ABOUT 102
#define ID_MENU_BANANA 103
#define IDB_BANANA_IMAGE 104
#define IDD_BANANA_DIALOG 105
#define IDC_BANANA_PICTURE 106
#define IDD_LOWRESPIC_DIALOG 107
#define IDC_LOWRESPIC_PICTURE 108
#define IDB_LOWRESPIC_IMAGE 109
#define ID_MENU_LOWRESPIC 110
#define IDC_MONITORINFO 101

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
